# Introduction to NumPy
This section provides an introduction to NumPy. NumPy is a very useful Python library for performing mathematical and logical operations on arrays.  Effective data-driven science and computation requires understanding how data is stored and manipulated. NumPy provides abundance useful features to implement efficient computations. 


In [2]:
# Importing NumPy with alias and looking its version
import numpy as np
np.__version__

'1.19.2'

In [3]:

arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# nested lists result in multi-dimensional arrays
arr1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr1

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# A List
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [6]:
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])