# Introduction to NumPy
This section provides an introduction to NumPy. NumPy is a very useful Python library for performing mathematical and logical operations on arrays.  Effective data-driven science and computation requires understanding how data is stored and manipulated. NumPy provides abundance useful features to implement efficient computations. 


In [1]:
# Importing NumPy with alias and looking its version
import numpy as np
np.__version__

'1.19.2'

NumPy is used to work with arrays. The array object in NumPy is called ndarray. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

Advantages of NumPy array over list:
* Save coding time: Array can directly handle arithmetic operations; no need of loops as a result many vector and matrix operations save coding time
* Faster execution: As the elements of the array are belonging to the same data type, there is no need of checking data types during execution; uses contiguous blockes of memory
* Uses less memory: No pointers are needed; type and itemsize are the same for the same columns

The following is the general difference between array and list data types:

| Array | List | 
|----|---|
| Only consists of elements belonging to the same data type | Can consist of elements belonging to different data types |
| No type checking at runtime | Type checking for each item |
| Type stored once in array metadata | Must store type for each item |
| Need to explicitly import a module for declaration | No need to explicitly import a module for declaration |
| Can directly handle arithmetic operations | Cannot directly handle arithmetic operations |
| Must contain either all nested elements of same size | Can be nested to contain different type of elements |
| Preferred for longer sequence of data items | Preferred for shorter sequence of data items |
| Less flexibility since addition, deletion has to be done element wise | Greater flexibility allows easy modification (addition, deletion) of data | 
| A loop has to be formed to print or access the components of array | The entire list can be printed without any explicit looping|	   
| Comparatively more compact in memory size | Consume larger memory for easy addition of elements |
| Faster, uses less memory | Slower,  uses ~3x more memory|



In [7]:
# Looking array versus list
my_list1 = [1, 2, 3, 4, 5]
print(my_list1)
print('Data type of my_list1',type(my_list1) )

my_array1 = np.arange(1, 6)  # Numpy array using arange() function
print(my_array1)
print('Data type of my_array1',type(my_array1))

my_list2 = list(range(1,6))
print(my_list2)
print('Data type of my_list2',type(my_list2) )

my_array2 = np.array(my_list2) # Numpy array from a list
print(my_array2)
print('Data type of my_array2',type(my_array2))

my_array3 = np.array(range(1,6)) # Numpy array from a range()
print(my_array3)
print('Data type of my_array2',type(my_array3))


[1, 2, 3, 4, 5]
Data type of my_list1 <class 'list'>
[1 2 3 4 5]
Data type of my_array1 <class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
Data type of my_list2 <class 'list'>
[1 2 3 4 5]
Data type of my_array2 <class 'numpy.ndarray'>
[1 2 3 4 5]
Data type of my_array2 <class 'numpy.ndarray'>


In [8]:
for i in range(len(my_list1)):
        my_list1[i] *= 3
        
# Notice the outputs using print function and putting the list name -- no difference
print(my_list1)
my_list1        

[3, 6, 9, 12, 15]


[3, 6, 9, 12, 15]

In [9]:
my_array1 *= 3

# Notice the outputs using print function and putting the array name with no print function
print(my_array1)
my_array1

[ 3  6  9 12 15]


array([ 3,  6,  9, 12, 15])

In [ ]:
arr = np.array(range(10))   # Numpy array from a range
print(arr)

In [ ]:
# nested lists result in multi-dimensional arrays 
arr1 = np.array([range(i, i + 3) for i in [2, 4, 6]])

arr1

In [ ]:
# A List
my_list = [1, 2, 3, 4, 5]
my_list

In [ ]:
# List to array
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

In [ ]:
#two-dimesional array from nested list
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

In [ ]:
# Numpy array using arrange() function
my_list = np.arange(10)
my_list