# Introduction to NumPy
This section provides an introduction to NumPy. NumPy is a very useful Python library for performing mathematical and logical operations on arrays.  Effective data-driven science and computation requires understanding how data is stored and manipulated. NumPy provides abundance useful features to implement efficient computations. 


In [4]:
# Importing NumPy with alias and looking its version
import numpy as np
np.__version__

'1.19.2'

NumPy is used to work with arrays. The array object in NumPy is called ndarray. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

Advantages of NumPy array over list:
* Save coding time: Array can directly handle arithmetic operations; no need of loops as a result many vector and matrix operations save coding time
* Faster execution: As the elements of the array are belonging to the same data type, there is no need of checking data types during execution; uses contiguous blockes of memory
* Uses less memory: No pointers are needed; type and itemsize are the same for the same columns

The following is the general difference between list and array data types:

| List | Array | 
|----|---|
|  Can consist of elements belonging to different data types | Only consists of elements belonging to the same data type |
| No need to explicitly import a module for declaration | Need to explicitly import a module for declaration |
| Cannot directly handle arithmetic operations  | Can directly handle arithmetic operations |
| Can be nested to contain different type of elements  | Must contain either all nested elements of same size |
| Preferred for shorter sequence of data items | Preferred for longer sequence of data items |
| Greater flexibility allows easy modification (addition, deletion) of data  | Less flexibility since addition, deletion has to be done element wise | 
| The entire list can be printed without any explicit looping	  | A loop has to be formed to print or access the components of array | 
| Consume larger memory for easy addition of elements| Comparatively more compact in memory size|


In [18]:
# Looking array versus list
my_list1 = [1, 2, 3, 4, 5]
print(my_list1)
print('Data type of my_list1',type(my_list1) )

my_array1 = np.arange(1, 6)  # Numpy array using arange() function
print(my_array1)
print('Data type of my_array1',type(my_array1))

my_list2 = list(range(1,6))
print(my_list2)
print('Data type of my_list2',type(my_list2) )

my_array2 = np.array(my_list2) # Numpy array from a list
print(my_array2)
print('Data type of my_array2',type(my_array2))

my_array3 = np.array(range(1,6)) # Numpy array from a range()
print(my_array3)
print('Data type of my_array2',type(my_array3))


[1, 2, 3, 4, 5]
Data type of my_list1 <class 'list'>
[1 2 3 4 5]
Data type of my_array1 <class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
Data type of my_list2 <class 'list'>
[1 2 3 4 5]
Data type of my_array2 <class 'numpy.ndarray'>
[1 2 3 4 5]
Data type of my_array2 <class 'numpy.ndarray'>


In [27]:
for i in range(len(my_list1)):
        my_list[i] *= 3
print(my_list)
my_list        

[27, 54, 81, 108, 135]


[27, 54, 81, 108, 135]

In [26]:
my_array1 *=3

# Notice the outputs using print function and putting the array name with no print function
print(my_array1)
my_array1

[ 81 162 243 324 405]


array([ 81, 162, 243, 324, 405])

In [20]:
arr = np.array(range(10))   # Numpy array from a range
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# nested lists result in multi-dimensional arrays 
arr1 = np.array([range(i, i + 3) for i in [2, 4, 6]])

arr1

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# A List
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [7]:
# List to array
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [9]:
#two-dimesional array from nested list
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [10]:
# Numpy array using arrange() function
my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])